### ISSUE TITLE
FID metric is returning NaNs

### ISSUE THREAD

**Issue by JessyD** [Project-MONAI/GenerativeModels#231]
As shown in this [notebook](https://github.com/Project-MONAI/GenerativeModels/commit/6227a172b938851426ba759e70299edb8a0b5927#diff-582b7304fb6667de4c3535ec5c898f7b529fa5b2b84f14bd271286284110227bR217) the FID returns NaN when given the synthetic and real images for the Hand dataset from MedNIST. However, as shown in this other [notebook](https://github.com/Project-MONAI/GenerativeModels/commit/6227a172b938851426ba759e70299edb8a0b5927#diff-2ec056afd2ae12145449b44b2010235d8ec58b5f1b7d7ede6f4e041fad55b774R318), the FID returns a value when using a test array.

**Comment by Warvito** [comment]
After adding `.double()` it is working as expected when conputing the FID of the mimic model https://github.com/Warvito/generative_mimic/blob/main/src/python/testing/compute_fid.py

**Comment by Warvito** [comment]
Since there is a discrepancy between the iterative approach and the original one, it will be better to adopt the original one
