### ISSUE TITLE
Fix torchscript error for AutoencoderKL

### ISSUE THREAD

**Issue by Warvito** [Project-MONAI/GenerativeModels#288]
I temporally remove the torchscript test from the AutoencoderKL 

https://github.com/Project-MONAI/GenerativeModels/blob/37d29530382127f408656115e55e46ed7c580306/tests/test_autoencoderkl.py#L146

For some reason it is generating problems when trying to use jit together with xformers, while the DiffusionModelUNet that have a similar usage of the package but do not raise issues.

**Comment by marksgraham** [comment]
Closing. I was told on MONAI Core that it isn't necessary these models pass torchscript tests. https://github.com/pytorch/pytorch/issues/103841 and may be replaced by another module.
