### ISSUE TITLE
Update the vq-vae+transformer tutorial to make use of the inferer class

### ISSUE THREAD

**Issue by marksgraham** [Project-MONAI/GenerativeModels#338]
The [VQ-VAE + transformer tutorial](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_vqvae_transformer/2d_vqvae_transformer_tutorial.ipynb) should make use of the `VQVAETransformerInferer` class instead of using custom functions for training and sampling

**Comment by Warvito** [comment]
Implements in #347
