### ISSUE TITLE
Add controllable image generation - Diffusion Autoencoders

### ISSUE THREAD

**Issue by SANCHES-Pedro** [Project-MONAI/GenerativeModels#346]
I was playing with [Diffusion Autoencoders](https://diff-ae.github.io/) from CVPR 2022 and thought we could include it here as part of the controllable generation models.

I will create a tutorial using the components that we already have. I think it's enough.

![image](https://user-images.githubusercontent.com/10501847/227776927-b0f68186-b7e7-4aa1-a28d-051609014e66.png)

**Comment by Warvito** [comment]
That sounds like a great addition! Thank you Pedro!
