### ISSUE TITLE
Error on MMD Metric

### ISSUE THREAD

**Issue by JessyD** [Project-MONAI/GenerativeModels#356]
The function that computes the MMD Metric is raising an error when calling its forward function:
```
mmd = MMD()
res = mmd(y, y_pred)
```
> TypeError: split expects at least a 1-dimensional tensor. `data` should be a batch-first tensor or a list of channel-first tensors, got <class 'torch.Tensor'>

However, no errors are returned when using:
```
mmd = MMD()
res = mmd._compute_metric(y, y_pred)
```

**Comment by Warvito** [comment]
Thanks for pointing this problem Jessica. I will have a look in the metric
