### ISSUE TITLE
Adding DDIM

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/GenerativeModels#366]
I was wondering if we consider adding DDIM to the repo.

https://huggingface.co/docs/diffusers/api/schedulers/ddim

**Comment by Warvito** [comment]
Hi @Can-Zhao, DDIMScheduler is already implemented in https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/schedulers/ddim.py .
You can find an example using it during inference to speed up the sampling time at https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/3d_ddpm/3d_ddpm_tutorial.ipynb

**Comment by Warvito** [comment]
PNDM is also implemented, and a comparison between the Schedulers can be found at https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_ddpm/2d_ddpm_compare_schedulers.ipynb

I guess one interesting addition could be showing in a tutorial how to use any Scheduler from the Diffuser package together with our models. What do you think?

**Comment by Can-Zhao** [comment]
Thank you!
