### ISSUE TITLE
Super resolation with stable diffusion via Autoencoderkl 256 to 256

### ISSUE THREAD

**Issue by AbrahamGhavabesh** [Project-MONAI/GenerativeModels#376]
@Warvito
Hi, I tried your model for training Autoencoderkl and Diffusion [your code:](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/2d_super_resolution/2d_stable_diffusion_v2_super_resolution.ipynb) for my personal program. It didn't work for higher resolutions than 6464(I test it on 256256) when I train autoencoderkl I get cude out of memory even choosing a smaller bach size I still get the same error. Is there any help to guide me??? Thanks a lot
`train_transforms = transforms.Compose(
    [
        transforms.LoadImaged(keys=["image"]),
        #transforms.Lambdad(keys="image", func=lambda x: x[:, :, 0]),
        transforms.EnsureChannelFirstd(keys=["image"]),
        transforms.ScaleIntensityRanged(keys=["image"], a_min=0.0, a_max=255.0, b_min=0.0, b_max=1.0, clip=True),
        transforms.RandAffined(
            keys=["image"],
            rotate_range=[(-np.pi / 36, np.pi / 36), (-np.pi / 36, np.pi / 36)],
            translate_range=[(-1, 1), (-1, 1)],
            scale_range=[(-0.05, 0.05), (-0.05, 0.05)],
            spatial_size=[256, 256],
            padding_mode="zeros",
            prob=0.5,
        ),
        transforms.CopyItemsd(keys=["image"], times=1, names=["low_res_image"]),
        transforms.Resized(keys=["low_res_image"], spatial_size=(128, 128)),
    ]
)
val_transforms = train_transforms

post_pred = Compose([EnsureType(), ])
post_label = Compose([EnsureType(), ])

train_ds = Dataset(data=train_files, transform=val_transforms)
train_loader = DataLoader(train_ds, batch_size=1, shuffle=False, num_workers=1, persistent_workers=True)

val_ds = Dataset(data=val_files, transform=val_transforms)
val_loader = DataLoader(val_ds, batch_size=1, shuffle=False, num_workers=1, persistent_workers=True)`

`autoencoderkl = AutoencoderKL(
    spatial_dims=2,               
    in_channels=1,              
    out_channels=1,               
    num_channels=(512, 512),
    latent_channels=4,           
    num_res_blocks=2,            
    norm_num_groups=16,           
    attention_levels=(False,True),  
)
autoencoderkl = autoencoderkl.to(device)

discriminator = PatchDiscriminator(spatial_dims=2, in_channels=1, num_layers_d=3, num_channels=64)
discriminator = discriminator.to(device) `

**Comment by marksgraham** [comment]
Hi @AbrahamGhavabesh 

You can reduce the memory footprint by reducing `num_channels` and/or increasing the number of levels - try something like
```
autoencoderkl = AutoencoderKL(
    spatial_dims=2,
    in_channels=1,
    out_channels=1,
    num_channels=(128, 256, 512),
    latent_channels=3,
    num_res_blocks=2,
    norm_num_groups=32,
    attention_levels=(False, False, True),
)
```

**Comment by AbrahamGhavabesh** [comment]
/

**Comment by AbrahamGhavabesh** [comment]
@marksgraham
Thank you for your reply.
I will explain my code in a better way as follow:
My images are 256*256 MRI  and I produce128*128 "low-resolution images from them to train the Diffusion model for making these "low-resolution" images "Higher resolution".
I did what you said and edit my autoecoderkl as follow:
```jupyter-notebook
#Define Autoencoderkl
autoencoderkl = AutoencoderKL(
    spatial_dims=2,               
    in_channels=1,              
    out_channels=1,               
    num_channels=(64,128,256, 512), 
    latent_channels=3,           
    num_res_blocks=2,            
    norm_num_groups=32,           
    attention_levels=(False,False, False, True),  
)
autoencoderkl = autoencoderkl.to(device)

``` 
well, it solves the problem and my autoencoderkl trained but I faced another problem which is the Diffusion model won't train because there are "Sizes of tensors must match except in dimension 1. Expected size 32 but got size 128 for tensor number 1 in the list"
the code and the error is below:
```jupyter-notebook
optimizer = torch.optim.Adam(unet.parameters(), lr=5e-5)

scaler_diffusion = GradScaler()

n_epochs = 1 #200
val_interval = 1 #20
epoch_loss_list = []
val_epoch_loss_list = []

for epoch in range(n_epochs):
    unet.train()
    autoencoderkl.eval()
    epoch_loss = 0
    progress_bar = tqdm(enumerate(train_loader), total=len(train_loader), ncols=110)
    progress_bar.set_description(f"Epoch {epoch}")
    for step, batch in progress_bar:
        images = batch["image"].to(device)
        low_res_image = batch["low_res_image"].to(device)
        optimizer.zero_grad(set_to_none=True)

        with autocast(enabled=True):
            with torch.no_grad():
                latent = autoencoderkl.encode_stage_2_inputs(images)* scale_factor 

            # Noise augmentation
            noise = torch.randn_like(latent).to(device)
            low_res_noise = torch.randn_like(low_res_image).to(device)
            timesteps = torch.randint(0, scheduler.num_train_timesteps, (latent.shape[0],), device=latent.device).long()
            low_res_timesteps = torch.randint(
                0, max_noise_level, (low_res_image.shape[0],), device=low_res_image.device
            ).long()

            noisy_latent = scheduler.add_noise(original_samples=latent, noise=noise, timesteps=timesteps)
            noisy_low_res_image = scheduler.add_noise(
                original_samples=low_res_image, noise=low_res_noise, timesteps=low_res_timesteps
            )
            print(" size of all") ####new
            print("images size = ", images.size()) ####new
            print("latent size = ", latent.size()) ####new
            print("noise size = ", noise.size()) ####new
            print("noisy_latent size = ", noisy_latent.size()) ####new
            print("noisy_low_res_image size = ", noisy_low_res_image.size()) ####new

            latent_model_input = torch.cat([noisy_latent, noisy_low_res_image], dim=1)

            noise_pred = unet(x=latent_model_input, timesteps=timesteps, class_labels=low_res_timesteps)
            loss = F.mse_loss(noise_pred.float(), noise.float())

        scaler_diffusion.scale(loss).backward()
        scaler_diffusion.step(optimizer)
        scaler_diffusion.update()

        epoch_loss += loss.item()

        progress_bar.set_postfix({"loss": epoch_loss / (step + 1)})
    epoch_loss_list.append(epoch_loss / (step + 1))

    if (epoch + 1) % val_interval == 0:
        unet.eval()
        val_loss = 0
        for val_step, batch in enumerate(val_loader, start=1):
            images = batch["image"].to(device)
            low_res_image = batch["low_res_image"].to(device)

            with torch.no_grad():
                with autocast(enabled=True):
                    latent = autoencoderkl.encode_stage_2_inputs(images) * scale_factor
                    # Noise augmentation
                    noise = torch.randn_like(latent).to(device)
                    low_res_noise = torch.randn_like(low_res_image).to(device)
                    timesteps = torch.randint(
                        0, scheduler.num_train_timesteps, (latent.shape[0],), device=latent.device
                    ).long()
                    low_res_timesteps = torch.randint(
                        0, max_noise_level, (low_res_image.shape[0],), device=low_res_image.device
                    ).long()

                    noisy_latent = scheduler.add_noise(original_samples=latent, noise=noise, timesteps=timesteps)
                    noisy_low_res_image = scheduler.add_noise(
                        original_samples=low_res_image, noise=low_res_noise, timesteps=low_res_timesteps
                    )

                    latent_model_input = torch.cat([noisy_latent, noisy_low_res_image], dim=1)
                    noise_pred = unet(x=latent_model_input, timesteps=timesteps, class_labels=low_res_timesteps)
                    loss = F.mse_loss(noise_pred.float(), noise.float())

            val_loss += loss.item()
        val_loss /= val_step
        val_epoch_loss_list.append(val_loss)
        print(f"Epoch {epoch} val loss: {val_loss:.4f}")

        # Sampling image during training
        sampling_image = low_res_image[0].unsqueeze(0)
        latents = torch.randn((1, 3, 32, 32)).to(device)
        low_res_noise = torch.randn((1, 1, 32, 32)).to(device)
        noise_level = 20
        noise_level = torch.Tensor((noise_level,)).long().to(device)
        noisy_low_res_image = scheduler.add_noise(
            original_samples=sampling_image,
            noise=low_res_noise,
            timesteps=torch.Tensor((noise_level,)).long().to(device),
        )

        scheduler.set_timesteps(num_inference_steps=1000)
        for t in tqdm(scheduler.timesteps, ncols=110):
            with torch.no_grad():
                with autocast(enabled=True):
                    latent_model_input = torch.cat([latents, noisy_low_res_image], dim=1)
                    noise_pred = unet(
                        x=latent_model_input, timesteps=torch.Tensor((t,)).to(device), class_labels=noise_level
                    )
                latents, _ = scheduler.step(noise_pred, t, latents)

        with torch.no_grad():
            decoded = autoencoderkl.decode_stage_2_outputs(latents / scale_factor)

        low_res_bicubic = nn.functional.interpolate(sampling_image, (64, 64), mode="bicubic")
        plt.figure(figsize=(2, 2))
        plt.style.use("default")
        plt.imshow(
            torch.cat([images[0, 0].cpu(), low_res_bicubic[0, 0].cpu(), decoded[0, 0].cpu()], dim=1),
            vmin=0,
            vmax=1,
            cmap="gray",
        )
        plt.tight_layout()
        plt.axis("off")
        plt.show()

``` 
And the error that i get is:
```jupyter-notebook
Epoch 0:   0%|                                                                          | 0/5 [00:00<?, ?it/s] size of all
images size =  torch.Size([10, 1, 256, 256])
latent size =  torch.Size([10, 3, 32, 32])
noise size =  torch.Size([10, 3, 32, 32])
noisy_latent size =  torch.Size([10, 3, 32, 32])
noisy_low_res_image size =  torch.Size([10, 1, 128, 128])

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-29-35e033c8a651>](https://localhost:8080/#) in <cell line: 10>()
     42             print("noisy_low_res_image size = ", noisy_low_res_image.size()) ####new
     43 
---> 44             latent_model_input = torch.cat([noisy_latent, noisy_low_res_image], dim=1)
     45 
     46             noise_pred = unet(x=latent_model_input, timesteps=timesteps, class_labels=low_res_timesteps)

1 frames
[/usr/local/lib/python3.9/dist-packages/torch/_tensor.py](https://localhost:8080/#) in __torch_function__(cls, func, types, args, kwargs)
   1293 
   1294         with _C.DisableTorchFunctionSubclass():
-> 1295             ret = func(*args, **kwargs)
   1296             if func in get_default_nowrap_functions():
   1297                 return ret

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 128 for tensor number 1 in the list.

``` 
Kindly any help is grateful

**Comment by marksgraham** [comment]
Hi,

You could try keeping a two level AE but reducing the number of channels to keep memory usage down. Does `num_channels=(128,128)` work for you?

**Comment by AbrahamGhavabesh** [comment]
> Hi,
> 
> You could try keeping a two level AE but reducing the number of channels to keep memory usage down. Does `num_channels=(128,128)` work for you?

hi
now i tried 128,128 but still have an error:
OutOfMemoryError: CUDA out of memory. Tried to allocate 5.00 GiB (GPU 0; 14.75 GiB total capacity; 9.15 GiB already allocated; 4.12 GiB free; 9.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by marksgraham** [comment]
I find I can train with batch size of 1 with these settings using 8GB of GPU memory:

```
autoencoderkl = AutoencoderKL(
    spatial_dims=2,
    in_channels=1,
    out_channels=1,
    num_channels=(128, 128),
    latent_channels=1,
    num_res_blocks=2,
    norm_num_groups=32,
    attention_levels=(False, False),
)
```

Using `attention_levels=(False, True),` uses more memory but you might just be able to fit it into your GPU.

**Comment by AbrahamGhavabesh** [comment]
> I find I can train with batch size of 1 with these settings using 8GB of GPU memory:
> 
> ```
> autoencoderkl = AutoencoderKL(
>     spatial_dims=2,
>     in_channels=1,
>     out_channels=1,
>     num_channels=(128, 128),
>     latent_channels=3,
>     num_res_blocks=2,
>     norm_num_groups=32,
>     attention_levels=(False, False),
> )
> ```
> 
> Using `attention_levels=(False, True),` uses more memory but you might just be able to fit it into your GPU.

i am going to try now

**Comment by AbrahamGhavabesh** [comment]
> > I find I can train with batch size of 1 with these settings using 8GB of GPU memory:
> > ```
> > autoencoderkl = AutoencoderKL(
> >     spatial_dims=2,
> >     in_channels=1,
> >     out_channels=1,
> >     num_channels=(128, 128),
> >     latent_channels=3,
> >     num_res_blocks=2,
> >     norm_num_groups=32,
> >     attention_levels=(False, False),
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using `attention_levels=(False, True),` uses more memory but you might just be able to fit it into your GPU.
> 
> i am going to try now

you don't know how much you helped me!! it works.
THankSSS A lot
merci
