### ISSUE TITLE
Add image-to-image translation tutorial (T1 to T2)

### ISSUE THREAD

**Issue by dyollb** [Project-MONAI/GenerativeModels#382]
Please add a tutorial illustrating how to train a model (e.g. 3d pix2pix, ..) to translate a T1 into a corresponding T2 (or CT, PS,...) image.

Dataset: IXI, ...

**Comment by khanwa** [comment]
Any updates on translating a T1 into a corresponding T2 (or CT, PS,...) image?

**Comment by marksgraham** [comment]
This isn't being worked on at the moment. The closest we have would be repurposing [this DDPM tutorial](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/image_to_image_translation/tutorial_segmentation_with_ddpm.ipynb) designed for segmentation. Replace the segmentation target with a paired T2 (or other modality) and you have image-to-image translation

**Comment by khanwa** [comment]
Thank you.

**Comment by virginiafdez** [comment]
Due to this issue being replied to and inactivity, I am closing this issue. On a last note, the ControlNet tutorial can also be applied to image-to-image translation tasks.
