### ISSUE TITLE
Fixed MONAI version in requirements may disrupt developer's environment

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/GenerativeModels#386]
In the requirement, the version of MONAI is fixed to:
```
monai-weekly==1.2.dev2304
```

Maybe we can provide a bit more flexibility for the developers by:

```
monai-weekly>=1.2.dev2304
```

**Comment by yiheng-wang-nv** [comment]
Agree.
Now when doing ` pip install monai-generative==0.2.1`, this specific monai version will be installed, the log is like:

```
Collecting monai-generative==0.2.1
  Downloading monai_generative-0.2.1-py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.5/134.5 kB 1.5 MB/s eta 0:00:00
Collecting monai-weekly==1.2.dev2304
  Downloading monai_weekly-1.2.dev2304-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.2 MB/s eta 0:00:00
```

When users use an env that already contain their expected monai version, it would introduce some errors.

Hi @ericspod , @Warvito , could you please help to fix this issue? Thanks in advance!

**Comment by mingxin-zheng** [comment]
In that case, 1.2dev2304 is released on Jan 23 2023. Any rc version >=1.2.0rc1 should include changes from that dev2304. I will create a PR for it.

https://pypi.org/project/monai-weekly/1.2.dev2304/
