### ISSUE TITLE
DiffusionModelUNet does not support torchscript

### ISSUE THREAD

**Issue by Can-Zhao** [Project-MONAI/GenerativeModels#387]
DiffusionModelUNet does not support torchscript

There might be other issues. What I found is:
Type | is not supported for torchscript.

https://github.com/Project-MONAI/GenerativeModels/blob/fd04ec6f98a1aec7b6886dff1cfb4d0fa72fe4fe/generative/networks/nets/diffusion_model_unet.py#L524

**Comment by ericspod** [comment]
Is this dependent on Python version? We can use `Optional` in this file instead if that's the only places where `|` is used.

**Comment by Warvito** [comment]
Similar to MONAI Core, we adopted the use of `from __future__ import annotations`  (https://github.com/Project-MONAI/MONAI/pull/5836) (I guess it was adopted due to the new Python3.10+ syntax).

**Comment by ericspod** [comment]
> Similar to MONAI Core, we adopted the use of `from __future__ import annotations` ([Project-MONAI/MONAI#5836](https://github.com/Project-MONAI/MONAI/pull/5836)) (I guess it was adopted due to the new Python3.10+ syntax) and replaced most Union and Optional for the new syntax.

That import was present at the top of the file in question so did that not work in this case?

**Comment by marksgraham** [comment]
@Can-Zhao did you make any progress with this when working on the diffusion bundle? I'm currently porting the networks to MONAI [pr here](https://github.com/Project-MONAI/MONAI/pull/7196) and running into this issue again...

**Comment by Can-Zhao** [comment]
> @Can-Zhao did you make any progress with this when working on the diffusion bundle? I'm currently porting the networks to MONAI [pr here](https://github.com/Project-MONAI/MONAI/pull/7196) and running into this issue again...

No I was not working on it...

**Comment by marksgraham** [comment]
Closing. I was told on MONAI Core that it isn't necessary these models pass torchscript tests. [Development of torchscript is frozen](https://github.com/pytorch/pytorch/issues/103841) and may be replaced by another module.
