### ISSUE TITLE
question: 2d_vqvae_tutorial.ipynb

### ISSUE THREAD

**Issue by maxshatskiy** [Project-MONAI/GenerativeModels#399]
Is there a way to use several GPUs for training? I have tried this notebook in kaggle, where one can use two T4 GPUs, but it uses only one.

**Comment by marksgraham** [comment]
In general its recommended to use [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html) to train with multiple GPUs. There is an example [here](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/distributed_training/ddpm_training_ddp.py). I don't think this approach is compatible with notebooks, though, you would have to use a python script. 

I think you might be able to use the simpler [DataParallel](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html) with a Jupyter notebook, but I've not tried myself.
