### ISSUE TITLE
Parameters that were not used in producing loss

### ISSUE THREAD

**Issue by juanprietob** [Project-MONAI/GenerativeModels#402]
When executing the model in parallel an error is triggered as a linear layer is not used in the forward function

https://github.com/Project-MONAI/GenerativeModels/blob/c1ec4ed4381de90ef18061c98624fa931c42e9b6/generative/networks/nets/diffusion_model_unet.py#L383

> Parameters which did not receive grad for rank 0: _forward_module.model.middle_block.attention.proj_attn.bias, _forward_module.model.middle_block.attention.proj_attn.weight, _forward_module.model.down_blocks.2.attentions.0.proj_attn.bias, _forward_module.model.down_blocks.2.attentions.0.proj_attn.weight, _forward_module.model.down_blocks.1.attentions.0.proj_attn.weight, _forward_module.model.down_blocks.1.attentions.0.proj_attn.bias, _forward_module.model.up_blocks.0.attentions.0.proj_attn.weight, _forward_module.model.up_blocks.0.attentions.0.proj_attn.bias, _forward_module.model.up_blocks.0.attentions.1.proj_attn.weight, _forward_module.model.up_blocks.0.attentions.1.proj_attn.bias, _forward_module.model.up_blocks.1.attentions.0.proj_attn.weight, _forward_module.model.up_blocks.1.attentions.0.proj_attn.bias, _forward_module.model.up_blocks.1.attentions.1.proj_attn.weight, _forward_module.model.up_blocks.1.attentions.1.proj_attn.bias

**Comment by marksgraham** [comment]
Can you try setting `find_unused_parameters=True` in the DDP constructor?
