### ISSUE TITLE
Move KLDLoss into the spade network

### ISSUE THREAD

**Issue by marksgraham** [Project-MONAI/GenerativeModels#409]
The [KLD loss](https://github.com/Project-MONAI/GenerativeModels/blob/72f0e5dfcb3ca375351b61527e1072384e9c3262/generative/losses/kld_loss.py) is currently only used in one place in the codebase, by the [SPADE network](https://github.com/Project-MONAI/GenerativeModels/blob/72f0e5dfcb3ca375351b61527e1072384e9c3262/generative/networks/nets/spade_network.py#L24). It is also not the general KLD loss but just covers a special case: the loss between a univariate Gaussian and another univariate Gaussian with zero mean and unit std. 

In anticipation of the port to MONAI Core, and given this loss does not seem to be more broadly useful in its current form, I propose moving it into the SPADE network file.

Does this sound sensible @ericspod ?

**Comment by ericspod** [comment]
Sounds good to me!
