### ISSUE TITLE
Question about DiffusionModel last layer zero_module

### ISSUE THREAD

**Issue by SophieOstmeier** [Project-MONAI/GenerativeModels#419]
I have more like a question.

I am using the DiffusionModel and in the last step, the h tensor is all zeros
<img width="444" alt="Screenshot 2023-08-24 at 12 16 17" src="https://github.com/Project-MONAI/GenerativeModels/assets/99991488/5743ad4c-962f-4d16-acaf-7793cf0fe55f">
The out function is defined 
<img width="598" alt="Screenshot 2023-08-24 at 12 20 13" src="https://github.com/Project-MONAI/GenerativeModels/assets/99991488/81e0cb49-d052-474a-9a95-2503d066e112">
Is there any reason, why zero_module is called?
For me, it makes less sense, because the output of the model is always all zeros and computing a gradients is always none.
Help is highly appreciated. And sorry in advance, if that is a basic question.

**Comment by marksgraham** [comment]
Hi,

We found it improved the performance of our models - this is referenced [here](https://github.com/Project-MONAI/GenerativeModels/pull/53#issuecomment-1327798113). 

This should not stop your model parameters from updating during training - is this something you have found in your experiments?

**Comment by SophieOstmeier** [comment]
Thanks for your reply and the reference! That makes sense now.
It took a couple of passes until I would not get a zero output, but then the weights updated to some non-zero value.

**Comment by bill-yc-chen** [comment]
May I ask, why we detach the gradient in the zero_module?
https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/nets/diffusion_model_unet.py#L68
Especially the final output layer use the zero_module.
https://github.com/Project-MONAI/GenerativeModels/blob/main/generative/networks/nets/diffusion_model_unet.py#L1856

This seems odd to me, like the whole final layer is untrainable and the parameters are always zero.
