### ISSUE TITLE
 I would like to generate multiple images at once.

### ISSUE THREAD

**Issue by dlsgurdlfkd** [Project-MONAI/GenerativeModels#424]
Hello, thank you for sharing this wonderful package.

http://generativemodels/model-zoo/models/cxr_image_synthesis_latent_diffusion_model/
I am running this code to create a chest dataset.

I run the code once and create one image. 
What code do I need to modify to continue creating images with a single run?

thank you.

**Comment by marksgraham** [comment]
Hi,

You would need to:

1) change `configs/inference.py` to have `"noise": "$torch.randn((n, 3, 64, 64)).to(@device)",` where `n` is your desired batch size
2) add `prompt_embeds = torch.cat([prompt_embeds] * n)` to the start of the `sampling_fn` in `scripts/sampler.py`
3) modify `scripts/saver.py` to have something like:

```
        for i in range(image_data.shape[0]):
            im = Image.fromarray(image_data[i, 0])
            im.save(self.output_dir + "/" + file_name + f"{i}.jpg")
```
