### ISSUE TITLE
monai.transforms.AddChanneld is deprecated

### ISSUE THREAD

**Issue by ilan-francisco** [Project-MONAI/GenerativeModels#427]
Hi, amazing project you guys have been working on. It has been very useful for me.

However, I found a small issue regarding the AddChanneld transform that you have in some of your scripts, which is deprecated and removed from monai. 

https://github.com/Project-MONAI/GenerativeModels/blob/1b34e60f80555e02036915224dd1783409095d3c/tutorials/generative/3d_ldm/3d_ldm_tutorial.py#L87C1-L87C48

Cheers!

**Comment by marksgraham** [comment]
Hi thanks for spotting this - will update!
