### ISSUE TITLE
AttributeError: module 'monai.transforms' has no attribute 'AddChanneld'

### ISSUE THREAD

**Issue by zapaishchykova** [Project-MONAI/GenerativeModels#432]
Hello there!
Thank you so much for your repo! I have an error "AttributeError: module 'monai.transforms' has no attribute 'AddChanneld'" in [2d_classifierfree_guidance_anomalydetection_tutorial.ipynb](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/anomaly_detection/2d_classifierfree_guidance_anomalydetection_tutorial.ipynb) notebook example(and in [this notebook too](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/anomaly_detection/anomalydetection_tutorial_classifier_guidance.ipynb)), and I think that is because AddChanneld is deprecated in Monai  1.1.0+ version. Do you have any tips on how to replace it? 
@Warvito @marksgraham

I have tried to use "transforms.EnsureChannelFirstd(keys=["image", "label"])," - but unfortunately thats not the same functionallity ( I think AddChanneld does expand image axis). Below attached is my monai version:
```
MONAI version: 1.3.0
Numpy version: 1.26.0
Pytorch version: 2.1.0+cu121
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 865972f7a791bf7b42efbcd87c8402bd865b329e
MONAI __file__: /home/<username>/anaconda3/envs/t1_c/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.3.0
Nibabel version: 5.1.0
scikit-image version: 0.22.0
scipy version: 1.11.3
Pillow version: 10.1.0
Tensorboard version: 2.15.0
gdown version: 4.7.1
TorchVision version: 0.16.0+cu121
tqdm version: 4.66.1
lmdb version: 1.4.1
psutil version: 5.9.3
pandas version: 2.1.1
einops version: 0.7.0
transformers version: 4.21.3
mlflow version: 2.7.1
pynrrd version: 1.0.0
clearml version: 1.13.1
```

I have tried to "dowgrade" the monai too to the version 1.1.0, but then unfortunatelly I cannot make the pytorch work (mismatch between drivers and cuda versions i guess). I have Nvidia A6000 if that helps!
Thanks!

**Comment by marksgraham** [comment]
Hey,

I actually fixed this today! It should be on the main branch. Can you install monai generative by cloning the latest version and running `pip install .` rather than installing through PyPi and see if that fixes it for you?

**Comment by zapaishchykova** [comment]
omg thats wonderful! Let me try that!

**Comment by zapaishchykova** [comment]
Hello,
Just tried that - I still get an error "AttributeError: module 'monai.transforms' has no attribute 'AddChanneld'" after cloning and installing from source

**Comment by ericspod** [comment]
Yes but I think you may need `channel_dim="no_channel"` to force adding a channel in.

**Comment by marksgraham** [comment]
Yeah sorry you didn't strictly need to reinstall the latest repo, rather just grab the latest version of the tutorial [here](https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/anomaly_detection/anomalydetection_tutorial_classifier_guidance.ipynb)

**Comment by zapaishchykova** [comment]
thank tou @marksgraham  and @ericspod, it all works now!
just gonna leave a solution here in case someone needs it:
```
train_transforms = transforms.Compose(
    [
        transforms.LoadImaged(keys=["image", "label"]),
        transforms.EnsureChannelFirstd(keys=["image", "label"]),
        transforms.Lambdad(keys=["image"], func=lambda x: x[channel, :, :, :]),
        transforms.EnsureChannelFirstd(keys=["image"], channel_dim="no_channel"),
        transforms.EnsureTyped(keys=["image", "label"]),
        transforms.Orientationd(keys=["image", "label"], axcodes="RAS"),
        transforms.Spacingd(keys=["image", "label"], pixdim=(3.0, 3.0, 2.0), mode=("bilinear", "nearest")),
        transforms.CenterSpatialCropd(keys=["image", "label"], roi_size=(64, 64, 44)),
        transforms.ScaleIntensityRangePercentilesd(keys="image", lower=0, upper=99.5, b_min=0, b_max=1),
        transforms.RandSpatialCropd(keys=["image", "label"], roi_size=(64, 64, 1), random_size=False),
        transforms.Lambdad(keys=["image", "label"], func=lambda x: x.squeeze(-1)),
        transforms.CopyItemsd(keys=["label"], times=1, names=["slice_label"]),
        transforms.Lambdad(keys=["slice_label"], func=lambda x: 0.0 if x.sum() > 0 else 1.0),
    ]
)
```
