### ISSUE TITLE
About sample size of DDPM

### ISSUE THREAD

**Issue by RunpuWei** [Project-MONAI/GenerativeModels#457]
Hello, thank you for your work. I want to use your work to complete DDPM Inpainting, but for my task (colonoscopy image), the size of 64x64 is a little too small, resize to 64x64 will lose a lot of semantic information. I want the model to be a 256x256 sample size, but I don't know how to change it. Please help me, thank you very much!

**Comment by marksgraham** [comment]
Hi, you should just be able to run your model on 256^2 images and it will run, the image size isn't hardcoded into the model architecture
