### ISSUE TITLE
Plans to add new advanced models? like consistency models, latent consistency models 

### ISSUE THREAD

**Issue by RiqiangGao** [Project-MONAI/GenerativeModels#459]
Hi, 

Thanks for this great work.  

Do you have plans to add more models like the  consistency models [1], latent consistency models [2]? 

Thanks,

[1] https://arxiv.org/abs/2303.01469
[2] https://arxiv.org/abs/2310.04378

**Comment by marksgraham** [comment]
Hi there,
We do plan to add new models. Currently our dev efforts are focused on porting this repo into the [core MONAI repo](https://github.com/Project-MONAI/MONAI). Once that is done we'll resume adding new features! Of course, any PRs adding new features are welcome at any time :)
