### ISSUE TITLE
Potentially wrong treshholding in a tutorial

### ISSUE THREAD

**Issue by iffthomas** [Project-MONAI/GenerativeModels#467]
Hi, Thank you very much for your work in generative models! It makes my life much easier.
I saw the tutorial https://github.com/Project-MONAI/GenerativeModels/blob/main/tutorials/generative/image_to_image_translation/tutorial_segmentation_with_ddpm.ipynb
for image segmentation. While replicating and looking through the code. The prediction output for the image(here the segmentation mask is in the range [-1,1]. However we treshhold it at >0.5 and not at 0 to get the binary prediction is this intended?

Kind Regards
Thomas

**Comment by JuliaWolleb** [comment]
Hi
Yes indeed, a threshold at 0 would make more sense if the images are in the range [-1,1]. Another way would be the Otsu threshold for each individual prediction.
Best,
Julia

**Comment by marksgraham** [comment]
the images are in the range [-1,1] but the labels are in the range [0,1] so the threshold of 0.5 used in this tutorial makes sense

**Comment by marksgraham** [comment]
actually looks like the images are also in the range [0,1]

**Comment by iffthomas** [comment]
Hi thank you all  for the responses, I've ran some tests and saw that the threshhold @0 doesnt perform at all but the treshhold at 0.5 is best. (haven't tested the otsu treshhold)
I was a bit suprised as I've assumed since my label values are either 0 or 1 and my image is in the range 0 and 1 why I even get negative values as a prediction but I guess I have reported the prediction only at an early stage of training. 

kind regards
thomas
