### ISSUE TITLE
Add different downsampling methods to PatchGAN discriminator

### ISSUE THREAD

**Issue by StijnvWijn** [Project-MONAI/GenerativeModels#475]
Dear Monai Team,

I have been working on generating synthetic images using a SPADE GAN similar to [this paper ](https://doi.org/10.1016/j.compmedimag.2022.102123) using the monai library and I noticed that your implementation of the PatchGAN discriminator differs slightly from theirs and [the official implementation](https://github.com/NVIDIA/pix2pixHD/blob/5a2c87201c5957e2bf51d79b8acddb9cc1920b26/models/networks.py#L292). The main difference is that instead of using a pooling kernel to change the receptive field, you seem to use an increasing amount of layers. I have done some experiments and for my use case, it seems that having a pooling operation improves my results. So my question is the following:

- Do you want me to create a PR to add the option for including a pooling operation or was there a reason for the current implementation?

**Comment by marksgraham** [comment]
Hi,

I think your proposed change would be good, as long as default behaviour doesn't change with the update, please go ahead with the PR :) 

Tagging @virginiafdez in case she has any comments too

**Comment by virginiafdez** [comment]
Hi! If I remember correctly, we changed the official implementation to make it compatible with other works that were part of the initial set of models that drove the start of this repo. These models used Patch-GAN, but not the pix2pixHD version, hence the difference. However, as long as the defaults don't change, it is great to have alternatives, especially if there's evidence that a certain combination of parameters leads to better results. Thanks!

**Comment by StijnvWijn** [comment]
Implemented in pull request #479 I was just unsure about whether to make the kernel size for the pooling operations another parameter or whether to stick with the same kernel size as the convolutions. For now I did the latter, let me know if you think another approach is better.
